name: freereg
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3.3
  - cudatoolkit=11.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
      - gradio==3.24.1
      - albumentations==1.3.0
      - opencv-contrib-python==4.3.0.36
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.5.9
      - omegaconf==2.3.0
      - test-tube>=0.7.5
      - streamlit==1.12.1
      - einops==0.6.0
      - transformers==4.29.2
      - webdataset==0.2.5
      - kornia==0.6.8
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==0.6.0
      - timm==0.6.7
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors==0.3.0
      - basicsr==1.4.2
      - wandb==0.14.0
      - open3d==0.12.0
      - tqdm==4.65.0
      - open-clip-torch==2.0.2
      - easydict==1.10