name: '3dmatch'

meta:
  base: 'data/3dmatch'
  feat_base: './tale_features'
  pair_type: 'overlap'
  overlap_pair: 0.3  
  seq_n_pair: 0 # no use
  rgb_size: [640,480]
  dpt_size: [640,480]
  rgb_intrinsic: [[585,0,320],[0,585,240],[0,0,1]]
  dpt_intrinsic: [[585,0,320],[0,585,240],[0,0,1]]
  dpt_scale: 1000.0
  densify: False

zoe:
  zoe_type: 'zoedepth'
  config_version: None
  zoe_ck: './tools/zoe/models/ZoeD_M12_N.pt'

feat:
  cn:
    save_layers: [0,4,6]
    seed: 12345
    prompt: 'a photo of a room, furniture, household items'
    step: 150
    check_layers: [0,4,6]
    pca_dim: 128
    top_crop: -1
    ckpts:
      basic: './tools/controlnet/models'
      yaml: 'control_v11f1p_sd15_depth.yaml'
      sd_ckpt: 'v1-5-pruned.ckpt'
      cn_ckpt: 'control_v11f1p_sd15_depth_ft.pth'

  fcgf:
    pth: './tools/fcgf/models/fcgf_indoor.pth'
    vs: 0.025
    trans_thres: 0.5

  merge:
    nkpts: -1

proj:
  filter_edge: True
  win_length: 3
  max_range_inwin: 0.2
  filter_far: True
  far_thres: 10
  filter_near: True
  near_thres: 0.01

match:
  dpt_mask:
    min: 0.01
    max: 10

reg:
  pnp:
    iters: 50000
    ird: 10
  ransac:
    iters: 50000
    dpt_ird: 0.1
    zoe_ird: 0.2

eval:
  mask:
    min: 0.01
    max: 10
  ir:
    thres: 0.3
  rr:
    r_thres: 20
    t_thres: 0.5

logfile: './result.txt'